repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args:
          - --enable=all
          - --std=c++20
          - --suppress=missingIncludeSystem
          - --suppress=unmatchedSuppression
          - --error-exitcode=1
          - -I
          - src
